sudo: false
language: cpp
addons:
script:
  - echo "OS": $TRAVIS_OS_NAME
  - $(CC) --version
  - $(CXX) --version
  - make dashing -j8
  - ./dashing dist bonsai/test/GCF_00*z
  - ./dashing dist -8 bonsai/test/GCF_00*z
  - ls bonsai/test/*.gz > fns.txt
  - cp fns.txt qns.txt
  - ./dashing dist --containment-index -Q qns.txt -F fns.txt
  - ./dashing dist -p4 --containment-index -Q qns.txt -F fns.txt
  - ./dashing dist -p4 --countmin --containment-index -Q qns.txt -F fns.txt
  - ./dashing dist --nearest-neighbors 2 -F fns.txt
  - if [ $TRAVIS_OS_NAME = linux ];
  - then
  -     gzip -d ./release/osx/dashing_s128.gz
  -     ./release/osx/dashing_s128 dist --containment-index -Q qns.txt -F fns.txt
  -     ./release/osx/dashing_s128 dist -p4 --containment-index -Q qns.txt -F fns.txt
  -     ./release/osx/dashing_s128 dist -p4 --countmin --containment-index -Q qns.txt -F fns.txt
  -     ./release/osx/dashing_s128 dist --nearest-neighbors 2 -F fns.txt
  - else
  -     gzip -d ./release/linux/dashing_s128.gz
  -     ./release/linux/dashing_s128 dist --containment-index -Q qns.txt -F fns.txt
  -     ./release/linux/dashing_s128 dist -p4 --containment-index -Q qns.txt -F fns.txt
  -     ./release/linux/dashing_s128 dist -p4 --countmin --containment-index -Q qns.txt -F fns.txt
  -     ./release/linux/dashing_s128 dist --nearest-neighbors 2 -F fns.txt
  - fi
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch

language: cpp
matrix:
  include:


    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5
        - CC=gcc-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
          - CXX=g++-6
          - CC=gcc-6

    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages: ['g++-6']
      env:
          - CXX=g++-6
          - CC=gcc-6

    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages: ['g++-7']
      env:
          - CXX=g++-7
          - CC=gcc-7



    - os: linux
      compiler: clang
      env:
          - CXX=clang++
          - CC=clang

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
          - CXX=clang++-3.5
          - CC=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
          - CXX=clang++-3.6
          - CC=clang-3.6


